
# Docker compose stack for continuous deployment:
# - External db is used, so it can expose port 5432 for SSH tunnels for shared tailormap-api development
# - The web-proxied service is put the "tailormap-snapshot" network so a proxy like Traefik can reverse proxy it for SSL termination

# Requires a PostgreSQL container named "tailormap-db" in an external network "tailormap-db".

# Extends the docker-compose.yml configuration:
# docker-compose -f docker-compose.yml -f docker-compose-cd.yml --profile proxied --profile full-external-db up -d

version: '3.9'

services:
  web-proxied:
    labels:
      traefik.http.routers.tailormap-snapshot.rule: "Host(`${HOSTNAME:-snapshot.tailormap.nl}`)"
      traefik.http.routers.tailormap-snapshot.tls: "true"
      traefik.http.routers.tailormap-snapshot.tls.certresolver: "letsencrypt"
      traefik.http.services.tailormap-snapshot.loadbalancer.server.port: 80
    networks:
      - tailormap-snapshot

  api:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tailormap-db/tailormap
      DB_PASSWORD: ${TAILORMAP_DB_PASSWORD:-tailormap}
    profiles:
      - full-external-db
    networks:
      - tailormap-snapshot
      - tailormap-db

  admin:
    environment:
      CATALINA_OPTS: -DPG_HOST=tailormap-db -DPG_PORT=5432 -DPG_DATABASE=tailormap -DDB_NAME=tailormap -DDB_USER=tailormap -DDB_PASSWORD=${TAILORMAP_DB_PASSWORD:-tailormap} -DURL_SCHEME=https
    profiles:
      - full-external-db
    networks:
      - tailormap-snapshot
      - tailormap-db

# The db container is not added to the full-external-db profile, so it won't run

networks:
  tailormap-snapshot:
  tailormap-db:
    external: true
