volumes:
  db:

services:
  tailormap:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ghcr.io/b3partners/tailormap:${VERSION:-snapshot}
    networks:
      - default
    expose:
      - 8080
    environment:
      - "HOST=${HOST:-localhost}"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db/tailormap"
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}"
      # The container binds to localhost for running the tailormap container by itself in host network mode
      # Change to 0.0.0.0 so it is reachable by reverse proxy such as Traefik
      - "SERVER_ADDRESS=0.0.0.0"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: ${TAILORMAP_DB_PASSWORD:-tailormap}
      POSTGRES_USER: tailormap
      POSTGRES_DB: tailormap
      PGUSER: postgres # for pg_isready
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: 'pg_isready -U tailormap'
    restart: unless-stopped
