volumes:
  db:

services:
  tailormap:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ghcr.io/b3partners/tailormap:${VERSION:-snapshot}
    # See README.md for how to build multi-arch images.
    # Run `DOCKER_BUILDKIT=0 docker compose build` if you want to use a locally modified ghcr.io/b3partners/tailormap-api image!
    build:
      context: .
      args:
        VERSION: ${VERSION:-snapshot}
        BASE_HREF: ${BASE_HREF:-/}
    networks:
      - default
    expose:
      - 8080
      - 8081 # for monitoring
    environment:
      - "HOST=${HOST:-localhost}"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db/tailormap"
      - "DB_PASSWORD=${TAILORMAP_DB_PASSWORD:-tailormap}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_PASSWORD: ${TAILORMAP_DB_PASSWORD:-tailormap}
      POSTGRES_USER: tailormap
      POSTGRES_DB: tailormap
      PGUSER: postgres # for pg_isready
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      interval: 1m
      timeout: 5s
      retries: 5
      test: pg_isready
    restart: unless-stopped
