volumes:
  db:

services:
  tailormap:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ghcr.io/b3partners/tailormap:${VERSION:-snapshot}
    networks:
      - default
    expose:
      - 8080
      - 8081 # for monitoring
    environment:
      - "HOST=${HOST:-localhost}"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db/tailormap"
      # This is set to localhost by default for running the tailormap container by itself in host network mode
      - "SERVER_ADDRESS=0.0.0.0"
      # Same for the management web endpoint, make it available to be scraped by Prometheus
      - "MANAGEMENT_SERVER_ADDRESS=0.0.0.0"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: ${TAILORMAP_DB_PASSWORD:-tailormap}
      POSTGRES_USER: tailormap
      POSTGRES_DB: tailormap
      PGUSER: postgres # for pg_isready
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      interval: 1m
      timeout: 5s
      retries: 5
      test: pg_isready
    restart: unless-stopped
