name: Docker Image

on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # TODO add some logic to determine version/tag name
      - name: Determine version
        run: |
          echo "VERSION_TAG=snapshot" >> $GITHUB_ENV

      - name: Build and Tag
        run: |
          docker build . -f Dockerfile --tag 'ghcr.io/b3partners/tailormap-viewer:${{ env.VERSION_TAG }}'

      - name: Start container
        run: |
          docker run --rm --name tailormap-viewer -h tailormap-viewer -d -p '8080:80' 'ghcr.io/b3partners/tailormap-viewer:${{ env.VERSION_TAG }}'

#      - name: Test container
#        run: |
#          docker logs tailormap-viewer
#          echo "Container running? "
#          docker inspect -f='{{json .State.Running}}' tailormap-viewer
#          echo "Container health: "
#          docker inspect -f='{{json .State.Health}}' tailormap-viewer
#          curl -Is http://localhost:8080/ | head -n 1

      - name: Log in and Push to registry
        # only publish when on main branch
#        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push 'ghcr.io/b3partners/tailormap-viewer:${{ env.VERSION_TAG }}'

      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST_SNAPSHOT }}
          context_name: 'dev-server'
          ssh_cert: ${{ secrets.DOCKER_HOST_SNAPSHOT_SSH_CERT }}
          ssh_key: ${{ secrets.DOCKER_HOST_SNAPSHOT_SSH_KEY }}
          use_context: true
      - run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml -f docker-compose-traefik.yml up -d
