name: "Release Drafter"

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
    name: Update release Draft
    steps:
      # Drafts next Release notes as Pull Requests are merged into "main"
      - uses: 'release-drafter/release-drafter@v5'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
