name: Renovate check

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4 * * SUN'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.238.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: '.github/renovate.json'
