name: Renovate check

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4 * * MON'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - name: Self-hosted Renovate
        uses: 'renovatebot/github-action@v34.124.5'
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: '.github/renovate.json'
